[DEFAULT]
; verbose mode
Verbose = true
; Path to KMC executable
KMCPath = kmc
; Path to KMC_Tools executable
KMCToolsPath = kmc_tools
; Number of processes (cpu count if not specified)
NumProcesses = 64
; Maximum memory (in GB)
MaxMemory = 128

; Species (homo_sapiens, mus_musculus)
Species = homo_sapiens
; Target gene ID
TargetGene = ENSG00000133703
; Length of candidate oligos
OligoLen = 16
; GC-content bound for candidate oligos
GCbound = 0.2,0.8
; Genome Assembly
GenomeAssembly = 38
; Ensemble Release
EnsembleRelease = 113

; Layout of kmer containing left_flank,core_region (gap),right_flank
MultiplicityLayout = 4,8,4

; maximum ddG from main target site for a repeated site to be included
RepeatedMaxddG = 5.0

; maximum ddG from main target site for a potential off-target site to be included
OffTargetMaxddG = 5.0
ddGTolerance = 5.0

; Absolute path for genome parent directory
GenomeDir = /home/ayat/Repositories/ASODesignPipeline/data/genome
; Absolute path for KMC temp data parent directory
KMCTempDir = /home/ayat/Repositories/ASODesignPipeline/data/
; Absolute path for job-specific data parent directory
JobDir = /home/ayat/Repositories/ASODesignPipeline/data

; Transcriptome support levels(can be a combination of tsl1,tsl2,tsl3,tsl4,tsl5,tslNA), refer to: https://www.ensembl.org/info/genome/genebuild/transcript_quality_tags.html. 
; Including all transcript support levels will increase the space required.
transcriptSupportLevels = 

; Only include protein coding genes
ProteinCodingOnly = true

; viennaRNA parameter file
RNACofoldParamFile=./vienna_rna_rna_params.par
; RNA cofold temperature
RNACofoldTemperature = 37.0

; Pedersen model parameters file
PedersenParamFile=./pedersen_params.json

; Add your own configuration below, 
; Any configuration below this line will override the default configuration if you run the script with the argument --args MY_CONFIG. 
; Example: python3 main.py --args MY_CONFIG

[BRCA2-protein_coding-16mer]
TargetGene = ENSG00000139618
ProteinCodingOnly = true
OligoLen = 16
MultiplicityLayout = 4,8,4

[BRCA2-protein_coding-20mer]
TargetGene = ENSG00000139618
ProteinCodingOnly = true
OligoLen = 20
MultiplicityLayout = 5,10,5

[BRCA2-all-20mer]
TargetGene = ENSG00000139618
ProteinCodingOnly = false
OligoLen = 20
MultiplicityLayout = 5,10,5

[BRCA2-all-16mer]
TargetGene = ENSG00000139618
ProteinCodingOnly = false
OligoLen = 16
MultiplicityLayout = 4,8,4

[KRAS-protein_coding-16mer]
TargetGene = ENSG00000133703
ProteinCodingOnly = true
OligoLen = 16
MultiplicityLayout = 4,8,4

[KRAS-all-16mer]
TargetGene = ENSG00000133703
ProteinCodingOnly = false
OligoLen = 16
MultiplicityLayout = 4,8,4

[KRAS-all-20mer]
TargetGene = ENSG00000133703
ProteinCodingOnly = false
OligoLen = 20
MultiplicityLayout = 5,10,5

[KRAS-protein_coding-20mer]
TargetGene = ENSG00000133703
ProteinCodingOnly = true
OligoLen = 20
MultiplicityLayout = 5,10,5
